// Central Font Awesome icon exports so components import from one place.
export { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
export {
  faBars,
  faChartColumn,
  faFolder,
  faFolderOpen,
  faFolderPlus,
  faXmark,
  faArrowLeft,
  faArrowUp,
  faPlus,
  faCircle,
  faChevronRight,
  faChevronDown,
  faGear,
  faRotateRight,
  faCheck,
  faCircleCheck,
  faCircleXmark,
  faCircleQuestion,
  faListCheck,
  faTerminal,
  faSpinner,
  faAnglesDown,
  faCircleStop,
  faClock,
  faCompress,
  faCodeBranch,
  faCode,
  faFileLines,
  faFloppyDisk,
  faUpRightFromSquare,
  faPencil,
  faMicrochip,
  faGaugeHigh,
  faVolumeHigh,
  faVolumeXmark,
  faPaperPlane,
  faLayerGroup,
} from "@fortawesome/free-solid-svg-icons";
